### ISSUE TITLE
Cannot import tmgen.uniform

### ISSUE THREAD

**Issue by yzexeter** [progwriter/TMgen#4]
I tried to install the package and followed the document at https://tmgen.readthedocs.io/en/latest/quickstart.html#download-and-installation, but it seems this can not work. No modules or available methods are inside the package.
Tried dir(tmgen), the output does not have modules like uniform.
I am wondering if how I can make it work.

**Comment by progwriter** [comment]
Hi @yzexeter, thank you for reporting this issue. 
This was a problem with documentation, the correct import statement is actually `from tmgen.models import uniform_tm`. I have updated the documentation to reflect this.

**Comment by yzexeter** [comment]
Thank you @progwriter for your help.
