### ISSUE TITLE
Computation of Traffic Matrices from Link Loads

### ISSUE THREAD

**Issue by ShawnshanksGui** [progwriter/TMgen#5]
Hi, I have some Link Loads data, and I want to Compute its' corresponding Traffic Matrices. How should I use this tool? 
Thanks!

Fei Gui

**Comment by progwriter** [comment]
Hi @ShawnshanksGui, currently this tool generates purely synthetic traffic matrices. If you already have empirical link-load data, I'd suggest looking at other techniques for generating traffic matrices 

This paper comes to mind: https://www.cs.utexas.edu/~yzhang/papers/tomogravity-sigm03.pdf, although there might be newer literature in this space.

**Comment by ShawnshanksGui** [comment]
Thanks a lot!
